# Generated by Django 5.0.6 on 2026-05-26 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sap_idoc", "SAP IDoc (MBGMCR03 flat file)"),
                            ("sap_odata", "SAP OData (S/4HANA Material Document API)"),
                            ("utility_green_button_csv", "Utility — Green Button CSV"),
                            ("utility_espi_xml", "Utility — ESPI XML"),
                            ("concur_expense_v3", "Concur Expense API v3"),
                            ("concur_itinerary_v1", "Concur Itinerary API v1"),
                            ("navan", "Navan"),
                        ],
                        max_length=50,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("connection_config", models.JSONField(blank=True, default=dict)),
                ("timezone", models.CharField(blank=True, default="", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_sources",
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                (
                    "country_code",
                    models.CharField(help_text="ISO 3166-1 alpha-2", max_length=2),
                ),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "grid_region",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "facilities",
                "db_table": "facilities",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="UomNormalizationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        help_text="'sap', 'utility', 'travel', or 'global'",
                        max_length=20,
                    ),
                ),
                ("raw_unit", models.CharField(max_length=20)),
                ("canonical_unit", models.CharField(max_length=20)),
                (
                    "conversion_factor",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "uom_normalization_rules",
            },
        ),
        migrations.CreateModel(
            name="MeterLocationMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "utility_usage_point_id",
                    models.CharField(
                        help_text="Green Button UsagePoint ID (utility-internal)",
                        max_length=200,
                    ),
                ),
                (
                    "meter_serial_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "service_account_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "commodity",
                    models.CharField(
                        default="electricity",
                        help_text="'electricity', 'gas', 'water'",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meter_mappings",
                        to="core.datasource",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meter_mappings",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meter_mappings",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "meter_location_mappings",
            },
        ),
        migrations.AddField(
            model_name="facility",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facilities",
                to="core.organization",
            ),
        ),
        migrations.CreateModel(
            name="ExpenseTypeCategoryMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_expense_type_code", models.CharField(max_length=50)),
                (
                    "raw_expense_type_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "canonical_activity",
                    models.CharField(
                        help_text="'flight', 'hotel', 'car_rental', 'taxi', 'personal_mileage', 'rail', 'not_esg_relevant'",
                        max_length=50,
                    ),
                ),
                ("ghg_scope", models.CharField(default="scope_3", max_length=10)),
                (
                    "ghg_category",
                    models.CharField(default="cat_6_business_travel", max_length=30),
                ),
                ("is_esg_relevant", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_mappings",
                        to="core.datasource",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_mappings",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "expense_type_category_mappings",
            },
        ),
        migrations.AddField(
            model_name="datasource",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="data_sources",
                to="core.organization",
            ),
        ),
        migrations.CreateModel(
            name="PlantLocationMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "werks",
                    models.CharField(
                        help_text="SAP plant code, e.g. DE01", max_length=4
                    ),
                ),
                (
                    "sap_plant_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plant_mappings",
                        to="core.datasource",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plant_mappings",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plant_mappings",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "plant_location_mappings",
            },
        ),
        migrations.AddConstraint(
            model_name="uomnormalizationrule",
            constraint=models.UniqueConstraint(
                fields=("source_system", "raw_unit"), name="uniq_uom_rule_per_system"
            ),
        ),
        migrations.AddIndex(
            model_name="meterlocationmapping",
            index=models.Index(
                fields=["utility_usage_point_id"], name="meter_locat_utility_09ae86_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="meterlocationmapping",
            constraint=models.UniqueConstraint(
                fields=("organization", "data_source", "utility_usage_point_id"),
                name="uniq_meter_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="expensetypecategorymapping",
            constraint=models.UniqueConstraint(
                fields=("organization", "data_source", "raw_expense_type_code"),
                name="uniq_expense_type_per_source",
            ),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["organization", "source_type"],
                name="data_source_organiz_55f219_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plantlocationmapping",
            index=models.Index(
                fields=["organization", "data_source", "werks"],
                name="plant_locat_organiz_ceb3e4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="plantlocationmapping",
            constraint=models.UniqueConstraint(
                fields=("organization", "data_source", "werks", "valid_from"),
                name="uniq_plant_mapping_per_source_date",
            ),
        ),
    ]
