# Generated by Django 5.0.6 on 2026-05-26 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        help_text="'sap_goods_movement', 'utility_interval', 'travel_air', 'travel_hotel', 'travel_car_rental', 'travel_personal_mileage'",
                        max_length=30,
                    ),
                ),
                ("staging_id", models.UUIDField(help_text="UUID of the staging row")),
                (
                    "staging_table",
                    models.CharField(
                        help_text="e.g. 'sap_goods_movement_staging'", max_length=60
                    ),
                ),
                (
                    "activity_date",
                    models.DateField(
                        help_text="Canonical date for ESG period bucketing (BUDAT for SAP)"
                    ),
                ),
                ("activity_period_start", models.DateField(blank=True, null=True)),
                ("activity_period_end", models.DateField(blank=True, null=True)),
                (
                    "location_country_code",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                (
                    "grid_region",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "ghg_scope",
                    models.CharField(
                        choices=[
                            ("scope_1", "Scope 1"),
                            ("scope_2", "Scope 2"),
                            ("scope_3", "Scope 3"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ghg_category",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "activity_type",
                    models.CharField(
                        help_text="e.g. 'diesel_combustion', 'grid_electricity', 'flight_economy_short_haul'",
                        max_length=80,
                    ),
                ),
                ("raw_quantity", models.DecimalField(decimal_places=6, max_digits=20)),
                ("raw_unit", models.CharField(max_length=20)),
                (
                    "normalized_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "normalized_unit",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "unit_conversion_factor",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "unit_conversion_source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="'uom_normalization_rules', 'manual', 'no_conversion_needed'",
                        max_length=50,
                    ),
                ),
                ("unit_conversion_notes", models.TextField(blank=True, default="")),
                (
                    "computed_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "distance_computation_method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="'great_circle×1.08_uplift', 'spend_proxy', 'reported' — required for audit so the emission method (distance vs spend) is explicit",
                        max_length=80,
                    ),
                ),
                ("is_reversal", models.BooleanField(default=False)),
                ("is_manually_edited", models.BooleanField(default=False)),
                (
                    "original_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of fields BEFORE the first manual edit",
                    ),
                ),
                ("edited_by", models.CharField(blank=True, default="", max_length=200)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("edit_reason", models.TextField(blank=True, default="")),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("ingested", "Ingested"),
                            ("flagged", "Flagged"),
                            ("analyst_reviewed", "Analyst Reviewed"),
                            ("approved", "Approved"),
                            ("locked", "Locked"),
                        ],
                        default="ingested",
                        max_length=20,
                    ),
                ),
                ("flagged_reason", models.TextField(blank=True, default="")),
                (
                    "reviewed_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, default="", max_length=200)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "staging_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Explanation of how this normalized row was derived",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_records",
                        to="core.datasource",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL if the source identifier was not yet mapped to a facility",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_records",
                        to="core.facility",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_records",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_records",
                        to="core.organization",
                    ),
                ),
                (
                    "reverses_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="activity.activityrecord",
                    ),
                ),
            ],
            options={
                "db_table": "activity_records",
                "ordering": ["-activity_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ingested", "Ingested"),
                            ("auto_flagged", "Auto-flagged by system"),
                            ("manually_flagged", "Manually flagged by analyst"),
                            ("unflagged", "Unflagged"),
                            ("analyst_reviewed", "Analyst reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("locked", "Locked"),
                            ("unlocked", "Unlocked"),
                            ("field_edited", "Field edited"),
                            ("calculation_rerun", "Calculation re-run"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("to_status", models.CharField(blank=True, default="", max_length=20)),
                (
                    "actor_id",
                    models.CharField(help_text="User ID or 'system'", max_length=200),
                ),
                (
                    "actor_display_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "field_changes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="For 'field_edited': [{field, old_value, new_value}]",
                    ),
                ),
                (
                    "activity_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_events",
                        to="activity.activityrecord",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_events",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "review_events",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="activityrecord",
            index=models.Index(
                fields=["organization", "review_status"],
                name="activity_re_organiz_68c3d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activityrecord",
            index=models.Index(
                fields=["organization", "ghg_scope", "activity_date"],
                name="activity_re_organiz_80505a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activityrecord",
            index=models.Index(
                fields=["facility", "activity_date"],
                name="activity_re_facilit_f9485b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityrecord",
            constraint=models.UniqueConstraint(
                fields=("staging_table", "staging_id"),
                name="uniq_activity_per_staging_row",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewevent",
            index=models.Index(
                fields=["activity_record", "-occurred_at"],
                name="review_even_activit_c983e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewevent",
            index=models.Index(
                fields=["organization", "-occurred_at"],
                name="review_even_organiz_ba3b3d_idx",
            ),
        ),
    ]
