# Generated by Django 5.0.6 on 2026-05-26 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        help_text="'scheduler', 'manual', 'webhook'", max_length=50
                    ),
                ),
                (
                    "triggered_by_user",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("rows_received", models.IntegerField(default=0)),
                ("rows_staged_ok", models.IntegerField(default=0)),
                ("rows_staged_warn", models.IntegerField(default=0)),
                ("rows_failed", models.IntegerField(default=0)),
                ("rows_duplicate", models.IntegerField(default=0)),
                ("source_date_range_start", models.DateField(blank=True, null=True)),
                ("source_date_range_end", models.DateField(blank=True, null=True)),
                ("error_summary", models.JSONField(blank=True, default=dict)),
                (
                    "raw_file_ref",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Path or URI to the original source file (S3 in production)",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_runs",
                        to="core.datasource",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_runs",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SapGoodsMovementStaging",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idoc_number", models.CharField(max_length=16)),
                ("idoc_type", models.CharField(default="MBGMCR03", max_length=30)),
                (
                    "idoc_message_type",
                    models.CharField(default="MBGMCR", max_length=30),
                ),
                (
                    "sender_partner",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "raw_budat",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="YYYYMMDD, verbatim",
                        max_length=8,
                    ),
                ),
                ("raw_bldat", models.CharField(blank=True, default="", max_length=8)),
                ("parsed_budat", models.DateField(blank=True, null=True)),
                ("parsed_bldat", models.DateField(blank=True, null=True)),
                ("ref_doc_no", models.CharField(blank=True, default="", max_length=16)),
                ("gm_code", models.CharField(blank=True, default="", max_length=2)),
                (
                    "item_line",
                    models.IntegerField(help_text="Position within the IDoc, 1-based"),
                ),
                ("matnr", models.CharField(blank=True, default="", max_length=18)),
                ("werks", models.CharField(blank=True, default="", max_length=4)),
                ("lgort", models.CharField(blank=True, default="", max_length=4)),
                ("bwart", models.CharField(blank=True, default="", max_length=3)),
                (
                    "entry_qnt",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                ("entry_uom", models.CharField(blank=True, default="", max_length=3)),
                ("ebeln", models.CharField(blank=True, default="", max_length=10)),
                ("ebelp", models.CharField(blank=True, default="", max_length=5)),
                ("bukrs", models.CharField(blank=True, default="", max_length=4)),
                ("lifnr", models.CharField(blank=True, default="", max_length=10)),
                (
                    "dmbtr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("waers", models.CharField(blank=True, default="", max_length=5)),
                ("is_reversal", models.BooleanField(default=False)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parse_warnings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{field, warning}] entries from the parser",
                    ),
                ),
                (
                    "staging_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("normalized", "Normalized"),
                            ("rejected", "Rejected"),
                            ("duplicate", "Duplicate"),
                            ("needs_uom_mapping", "Needs Uom Mapping"),
                            ("needs_plant_mapping", "Needs Plant Mapping"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sap_staging_rows",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sap_staging_rows",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "sap_goods_movement_staging",
            },
        ),
        migrations.CreateModel(
            name="TravelExpenseStaging",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        help_text="'concur', 'navan', 'amex_gbt'", max_length=20
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        help_text="'expense_entry', 'air_segment', 'hotel_segment', 'car_segment'",
                        max_length=20,
                    ),
                ),
                (
                    "concur_report_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "concur_entry_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "expense_type_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "expense_type_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "spend_category_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("transaction_date", models.DateField(blank=True, null=True)),
                (
                    "transaction_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "transaction_currency",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                (
                    "vendor_description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "location_name",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "location_country",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_personal", models.BooleanField(default=False)),
                (
                    "journey_distance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "distance_unit",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("comment_text", models.TextField(blank=True, default="")),
                (
                    "itinerary_booking_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "linked_itinerary_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("origin_iata", models.CharField(blank=True, default="", max_length=3)),
                (
                    "destination_iata",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                (
                    "class_of_service",
                    models.CharField(blank=True, default="", max_length=1),
                ),
                (
                    "aircraft_iata_code",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                (
                    "flight_number",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("departure_datetime", models.DateTimeField(blank=True, null=True)),
                ("arrival_datetime", models.DateTimeField(blank=True, null=True)),
                ("hotel_checkin_date", models.DateField(blank=True, null=True)),
                ("hotel_checkout_date", models.DateField(blank=True, null=True)),
                ("room_nights", models.IntegerField(blank=True, null=True)),
                (
                    "car_acriss_code",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                ("car_rental_start", models.DateField(blank=True, null=True)),
                ("car_rental_end", models.DateField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("parse_warnings", models.JSONField(blank=True, default=list)),
                (
                    "staging_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("normalized", "Normalized"),
                            ("rejected", "Rejected"),
                            ("duplicate", "Duplicate"),
                            ("needs_uom_mapping", "Needs Uom Mapping"),
                            ("needs_plant_mapping", "Needs Plant Mapping"),
                            (
                                "needs_expense_type_mapping",
                                "Needs expense type mapping",
                            ),
                            (
                                "no_itinerary_linkage",
                                "No itinerary linkage (spend-only)",
                            ),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="travel_staging_rows",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="travel_staging_rows",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "travel_expense_staging",
            },
        ),
        migrations.CreateModel(
            name="UtilityIntervalStaging",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("utility_usage_point_id", models.CharField(max_length=200)),
                (
                    "source_format",
                    models.CharField(
                        default="green_button_csv",
                        help_text="'green_button_csv', 'espi_xml', 'green_button_cmd'",
                        max_length=30,
                    ),
                ),
                ("raw_date", models.CharField(blank=True, default="", max_length=20)),
                (
                    "raw_start_time",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "raw_end_time",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("raw_usage", models.CharField(blank=True, default="", max_length=30)),
                ("raw_units", models.CharField(blank=True, default="", max_length=20)),
                ("raw_cost", models.CharField(blank=True, default="", max_length=30)),
                ("raw_notes", models.TextField(blank=True, default="")),
                (
                    "espi_interval_start_epoch",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "espi_interval_duration_s",
                    models.IntegerField(blank=True, null=True),
                ),
                ("espi_value_raw", models.BigIntegerField(blank=True, null=True)),
                ("espi_power_of_ten_mult", models.IntegerField(blank=True, null=True)),
                ("espi_uom_code", models.IntegerField(blank=True, null=True)),
                ("espi_reading_quality", models.IntegerField(blank=True, null=True)),
                ("interval_start", models.DateTimeField(blank=True, null=True)),
                ("interval_end", models.DateTimeField(blank=True, null=True)),
                ("interval_length_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "usage_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("usage_unit", models.CharField(blank=True, default="", max_length=10)),
                (
                    "cost_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "cost_currency",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                ("is_estimated", models.BooleanField(default=False)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("parse_warnings", models.JSONField(blank=True, default=list)),
                (
                    "staging_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("normalized", "Normalized"),
                            ("rejected", "Rejected"),
                            ("duplicate", "Duplicate"),
                            ("needs_uom_mapping", "Needs Uom Mapping"),
                            ("needs_plant_mapping", "Needs Plant Mapping"),
                            ("needs_meter_mapping", "Needs meter mapping"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utility_staging_rows",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utility_staging_rows",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "utility_interval_staging",
            },
        ),
        migrations.AddIndex(
            model_name="ingestionrun",
            index=models.Index(
                fields=["organization", "data_source", "-started_at"],
                name="ingestion_r_organiz_fd714a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sapgoodsmovementstaging",
            index=models.Index(
                fields=["organization", "staging_status"],
                name="sap_goods_m_organiz_815369_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sapgoodsmovementstaging",
            index=models.Index(
                fields=["ingestion_run"], name="sap_goods_m_ingesti_1e79e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sapgoodsmovementstaging",
            index=models.Index(fields=["werks"], name="sap_goods_m_werks_395a63_idx"),
        ),
        migrations.AddConstraint(
            model_name="sapgoodsmovementstaging",
            constraint=models.UniqueConstraint(
                fields=("organization", "idoc_number", "item_line"),
                name="uniq_sap_staging_per_idoc_item",
            ),
        ),
        migrations.AddIndex(
            model_name="travelexpensestaging",
            index=models.Index(
                fields=["organization", "staging_status"],
                name="travel_expe_organiz_9e868c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="travelexpensestaging",
            index=models.Index(
                fields=["itinerary_booking_id"], name="travel_expe_itinera_58ff00_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="travelexpensestaging",
            constraint=models.UniqueConstraint(
                condition=models.Q(("concur_entry_id__gt", "")),
                fields=("organization", "source_system", "concur_entry_id"),
                name="uniq_travel_per_concur_entry",
            ),
        ),
        migrations.AddIndex(
            model_name="utilityintervalstaging",
            index=models.Index(
                fields=["organization", "staging_status"],
                name="utility_int_organiz_2672d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="utilityintervalstaging",
            index=models.Index(
                fields=["utility_usage_point_id", "interval_start"],
                name="utility_int_utility_fdf2bc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="utilityintervalstaging",
            constraint=models.UniqueConstraint(
                condition=models.Q(("interval_start__isnull", False)),
                fields=("organization", "utility_usage_point_id", "interval_start"),
                name="uniq_utility_per_meter_interval",
            ),
        ),
    ]
