# Generated by Django 5.0.6 on 2026-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sapgoodsmovementstaging",
            name="raw_bldat",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="sapgoodsmovementstaging",
            name="raw_budat",
            field=models.CharField(
                blank=True,
                default="",
                help_text="YYYYMMDD per spec, but stored verbatim",
                max_length=20,
            ),
        ),
    ]
